Subtract the 1D Array *arr2* from the 2D array *arr1*, such that each item of *arr2* subtracts from respective row of *arr1*

Ex

arr1 = `[[x1, x2 , x3], [y1, y2, y3], [z1,z2,z3]]`

arr2 = `[x,y,z]`

Result `[ [ x1-x, x2-x, x3-x],` etc

In [174]:
#Name:Deepti Nair
#email:dnair1@uncc.edu

import numpy as np
a = np.arange(15).reshape(3, 5)
b = np.arange(3)
for i in range(len(a)):
    for j in range(len(b)):
        if(i==j):
            print(a[i]-b[j])
          



[0 1 2 3 4]
[4 5 6 7 8]
[ 8  9 10 11 12]


Given a 1D Array, find the local maxima (numbers surrounded by 2 smaller numbers)

In [175]:
#Print the number which is bigger and surrounded by two smaller numbers
p = np.array([(100,2,3,1,4,3,6,20)])
max = 0
for i in range(len(p)):
    max = 0
    s = p.size
    for j in range(1,s-1):
        if(p[i][j]>p[i][j+1] and p[i][j]>p[i][j-1]):
            if(max < p[i][j]):
                max = p[i][j]
print(max)

4


Given two n x m Arrays, compute the average of elements in matching subarrays

Ex

arr1      
`[[1,1],[2,2],[3,3]]`

arr2      
`[[1,1],[2,2],[3,3]]`

result:
`[1,2,3]`



In [177]:

x = [[10, 20], [20, 20],[30, 10]]
y = [[20, 10], [20, 20],[90, 30]]
avgLst = []

for i,j in zip(x,y):
    val = 0
    totalLen = len(i)+len(j)
    for ii in range(len(i)):
        val += i[ii]
    for jj in range(len(j)):
        val += j[jj]
    avgLst.append(int(val/totalLen))
print(avgLst)


[15, 20, 40]
